from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any


@dataclass(frozen=True)
class CapabilitySpec:
    name: str
    category: str
    layer: str
    description: str
    endpoints: tuple[str, ...] = ()
    actions: tuple[str, ...] = ()
    input_schema: dict[str, Any] = field(default_factory=dict)
    output_schema: dict[str, Any] = field(default_factory=dict)
    deterministic: bool = True
    changes_state: bool = False
    risk: str = "low"
    owner: str = "deterministic_router"
    preconditions: tuple[str, ...] = ()
    success_signals: tuple[str, ...] = ()
    fallback_to: tuple[str, ...] = ()
    milestones: tuple[str, ...] = ()
    enabled: bool = True
    cost: str = "low"

    def to_dict(self) -> dict[str, Any]:
        return {
            "name": self.name,
            "category": self.category,
            "layer": self.layer,
            "description": self.description,
            "endpoints": list(self.endpoints),
            "actions": list(self.actions),
            "input_schema": dict(self.input_schema),
            "output_schema": dict(self.output_schema),
            "deterministic": self.deterministic,
            "changes_state": self.changes_state,
            "risk": self.risk,
            "owner": self.owner,
            "preconditions": list(self.preconditions),
            "success_signals": list(self.success_signals),
            "fallback_to": list(self.fallback_to),
            "milestones": list(self.milestones),
            "enabled": self.enabled,
            "cost": self.cost,
        }


def build_default_capability_manifest() -> dict[str, CapabilitySpec]:
    specs = [
        CapabilitySpec(
            name="capability_router",
            category="planning",
            layer="intent_planning",
            description="Classifies task intent, ranks deterministic capabilities, builds fallback order, attaches non-blocking runtime preflight and crawl_efficiency_plan.v1 propagation plus frontend crawl efficiency UI/Markdown summaries, propagates efficiency_correlation_report.v1 through execute telemetry and frontend summaries, records runtime context/drift/issues and successful or failed browser action traces for capability execution, bundles failed action/runtime context, projects it into planner feedback, converts failed trace artifacts into regression fixtures through helper/API/frontend paths, validates failure fixtures against route/planner feedback replay through helper/API/frontend paths, lists saved failure fixture artifacts for regression libraries through API/frontend paths, replays fixture batches offline through API/frontend paths with triage summaries and copied Markdown summaries, lists saved batch replay reports through API/frontend history views with latest-vs-previous trend deltas, reuses one phase-event contract for telemetry and replayable error detail, supports replaying capability execute trace artifacts, and projects runtime plus browser action failure taxonomy and recovery guidance into capability trace health, searchable row previews, UI issue chips, and copied Markdown summaries.",
            endpoints=("POST /api/capabilities/route", "POST /api/capabilities/plan", "POST /api/capabilities/execute", "GET /api/capabilities/agent_case_benchmark", "POST /api/capabilities/agent_case_benchmark", "GET /api/capabilities/agent_case_regression", "POST /api/capabilities/agent_case_regression", "POST /api/capabilities/run_evidence_bundle", "GET /api/capabilities/browser_runtime_doctor", "POST /api/capabilities/browser_runtime_doctor", "POST /api/capabilities/failure_fixture", "GET /api/capabilities/failure_fixtures", "POST /api/capabilities/failure_fixture/replay", "POST /api/capabilities/failure_fixture/replay_batch", "GET /api/capabilities/failure_fixture/replay_batches", "POST /api/capabilities/efficiency_feedback/replay", "POST /api/capabilities/efficiency_feedback/shadow", "GET /api/capabilities/efficiency_feedback/replays", "POST /api/capabilities/efficiency_feedback/replay_batch"),
            input_schema={"goal": "str", "url": "str", "context": "dict"},
            output_schema={"intent": "dict", "backend_plan": "list", "runtime_preflight": "dict", "crawl_efficiency_plan": "crawl_efficiency_plan.v1", "agent_case_benchmark_matrix": "agent_case_benchmark_matrix.v1", "agent_case_benchmark_result": "agent_case_benchmark_result.v1", "agent_case_regression_report": "agent_case_regression_report.v1", "run_evidence_bundle": "run_evidence_bundle.v1", "browser_runtime_doctor_report": "browser_runtime_doctor_report.v1", "efficiency_correlation_report": "efficiency_correlation_report.v1", "efficiency_feedback_replay_report": "efficiency_feedback_replay_report.v1", "efficiency_feedback_replay_reports": "list[efficiency_feedback_replay_report_summary.v1]", "efficiency_feedback_replay_batch_report": "efficiency_feedback_replay_batch_report.v1", "planner_feedback_shadow_report": "planner_feedback_shadow_report.v1", "execution_plan": "dict", "planner_feedback": "planner_feedback.v1", "failure_fixture_replay_report": "capability_failure_fixture_replay_report.v1", "failure_fixture_replay_batch_report": "capability_failure_fixture_replay_batch_report.v1", "failure_fixture_replay_batch_history_trend": "capability_failure_fixture_replay_batch_history_trend.v1", "runtime_context": "dict", "runtime_summary": "dict", "runtime_drift": "dict", "runtime_issue_summary": "dict", "action_trace": "browser_action_trace.v1", "action_issue_summary": "browser_action_issue_summary.v1", "failure_bundle": "capability_execute_failure_bundle.v1", "failure_regression_fixture": "capability_failure_regression_fixture.v1"},
            deterministic=True,
            changes_state=False,
            owner="deterministic_router",
            success_signals=("intent.task_type", "backend_plan", "fallback_chain", "runtime_preflight.status", "crawl_efficiency.recommended_path", "crawl_efficiency.skip_browser", "crawl_efficiency.skip_vlm", "runtime_context.after.runtime_preflight.status", "runtime_drift.status", "runtime_issue_summary.status", "capability_execute.action_trace", "capability_execute.failed_action_trace", "capability_execute.action_issue_summary.status", "capability_execute.failure_bundle", "capability_execute.crawl_efficiency_plan", "capability_execute.efficiency_correlation_report", "capability_router.planner_feedback", "execution_plan.planner_feedback", "capability_execute.error_detail_phase_event", "capability_execute.phase_event_contract", "capability_trace.artifact_replay", "capability_trace.failure_regression_fixture", "capability_trace.failure_fixture_api", "capability_trace.failure_fixture_ui", "capability_trace.failure_fixture_library", "capability_trace.failure_fixture_library_ui", "capability_trace.failure_fixture_replay", "capability_trace.failure_fixture_replay_api", "capability_trace.failure_fixture_replay_ui", "capability_trace.failure_fixture_replay_batch", "capability_trace.failure_fixture_replay_batch_ui", "capability_trace.failure_fixture_replay_batch_triage", "capability_trace.failure_fixture_replay_batch_markdown_summary", "capability_trace.failure_fixture_replay_batch_history", "capability_trace.failure_fixture_replay_batch_history_trend", "capability_trace.runtime_codes", "capability_trace.preflight_codes", "capability_trace.action_codes", "capability_trace.action_issue_summary", "capability_trace.action_failure_taxonomy", "capability_trace.action_recovery_actions", "capability_trace.error_detail_action_trace", "capability_trace.action_search", "capability_trace.health_alignment", "capability_trace.markdown_summary", "capability_trace.crawl_efficiency_ui", "capability_trace.crawl_efficiency_markdown_summary", "capability_trace.efficiency_correlation_ui", "capability_trace.efficiency_correlation_markdown_summary"),
            fallback_to=("semantic_planner_reflector",),
            milestones=("Y29", "Y43", "Y44", "Y53", "Y54", "Y55", "Y56", "Y57", "Y58", "Y59", "Y60", "Y61", "Y62", "Y63", "Y64", "Y65", "Y66", "Y73", "Y74", "Y75", "Y77", "Y78", "Y79", "Y80", "Y81", "Y84", "Y85", "Y86", "Y87", "Y88", "Y89", "Y90", "Y91", "Y92", "Y93", "Y94", "Y95", "Y96", "Y97", "Y98", "Y109", "Y110", "Y112", "Y115", "Y116", "Y117", "Y118", "Y119", "Y120", "Y121", "Y122", "Y124"),
        ),
        CapabilitySpec(
            name="crawl_efficiency_planner",
            category="planning",
            layer="intent_planning",
            description="Ranks crawl and control paths by efficiency so API replay, HTML extraction, DOM selectors, and targeted probes are preferred before browser actions and final VLM grounding.",
            input_schema={"payload": "dict", "route": "dict", "network_candidates": "list", "browser_state": "browser_state.v2", "runtime_status": "dict"},
            output_schema={"plan": "crawl_efficiency_plan.v1"},
            deterministic=True,
            changes_state=False,
            owner="deterministic_router",
            success_signals=("crawl_efficiency.recommended_path", "crawl_efficiency.skip_browser", "crawl_efficiency.skip_vlm", "crawl_efficiency.available_paths"),
            fallback_to=("api_replay", "generic_extractor", "browser_control", "vision_agent"),
            milestones=("Y108",),
        ),
        CapabilitySpec(
            name="run_registry",
            category="observability",
            layer="operations_plane",
            description="Tracks task lifecycle, final status, run metadata, and historical run lookup.",
            endpoints=("GET /api/runs", "GET /api/runs/{run_id}"),
            output_schema={"runs": "list", "status": "str"},
            deterministic=True,
            changes_state=False,
            owner="runtime_guards",
            success_signals=("run_id", "status", "finished_at"),
            milestones=("Y1",),
        ),
        CapabilitySpec(
            name="task_queue",
            category="orchestration",
            layer="operations_plane",
            description="Provides pause, retry, resume, recovery, heartbeat, watchdog, and queue metrics for long-running work.",
            endpoints=("GET /api/task_queue", "POST /api/task_queue/recover", "POST /api/task_queue/watchdog", "GET /api/task_queue/metrics"),
            deterministic=True,
            changes_state=True,
            owner="runtime_guards",
            success_signals=("queue_state", "worker_state", "metrics"),
            fallback_to=("human_guard",),
            milestones=("Y7", "Y17"),
        ),
        CapabilitySpec(
            name="universal_benchmark",
            category="quality_gate",
            layer="operations_plane",
            description="Builds an offline coverage matrix and result summary for universal crawling and control surfaces such as API-backed pages, tables, cards, pagination, forms, rich components, iframes, shadow DOM, uploads, downloads, and auth walls.",
            output_schema={"matrix": "universal_benchmark_matrix.v1", "result": "universal_benchmark_result.v1"},
            deterministic=True,
            changes_state=False,
            owner="runtime_guards",
            success_signals=("coverage.required_surfaces", "coverage.coverage_gaps", "result.pass_rate", "result.weak_dimensions", "result.recommended_focus"),
            fallback_to=("failure_fixture_replay", "extraction_snapshot_replay"),
            milestones=("Y105",),
        ),
        CapabilitySpec(
            name="agent_case_benchmark",
            category="quality_gate",
            layer="operations_plane",
            description="Builds an offline project-level matrix and result summary for representative VSpider agent cases so optimization work is guided by real task surfaces, route capability expectations, risk tags, and pass-rate weak dimensions.",
            endpoints=("GET /api/capabilities/agent_case_benchmark", "POST /api/capabilities/agent_case_benchmark"),
            input_schema={"cases": "list[agent_case]", "results": "list[agent_case_result]"},
            output_schema={"matrix": "agent_case_benchmark_matrix.v1", "result": "agent_case_benchmark_result.v1"},
            deterministic=True,
            changes_state=False,
            owner="runtime_guards",
            success_signals=("agent_case_benchmark.coverage", "agent_case_benchmark.route_capabilities", "agent_case_benchmark.risk_tags", "agent_case_benchmark.pass_rate", "agent_case_benchmark.weak_dimensions", "agent_case_benchmark.recommended_focus", "agent_case_regression.gate", "agent_case_regression.trend"),
            fallback_to=("universal_benchmark", "failure_fixture_replay", "extraction_snapshot_replay"),
            milestones=("Y120",),
        ),
        CapabilitySpec(
            name="agent_case_regression_runner",
            category="quality_gate",
            layer="operations_plane",
            description="Builds an offline regression gate from selected real agent cases, existing run_agent_cases reports, benchmark summaries, thresholds, and latest-vs-previous trend so case automation can be checked without starting browsers from the API.",
            endpoints=("GET /api/capabilities/agent_case_regression", "POST /api/capabilities/agent_case_regression"),
            input_schema={"cases": "list[agent_case]", "results": "list[agent_case_result]", "report_paths": "list[path]", "thresholds": "dict"},
            output_schema={"report": "agent_case_regression_report.v1"},
            deterministic=True,
            changes_state=False,
            owner="runtime_guards",
            success_signals=("agent_case_regression.selected_count", "agent_case_regression.summary.pass_rate", "agent_case_regression.gate.status", "agent_case_regression.trend.direction", "agent_case_regression.command"),
            fallback_to=("agent_case_benchmark", "run_evidence_bundle", "failure_fixture_replay"),
            milestones=("Y124",),
        ),
        CapabilitySpec(
            name="run_evidence_bundle",
            category="observability",
            layer="operations_plane",
            description="Aggregates route, execution_plan, runtime, browser state, action traces, extraction evidence, failure bundles, artifacts, and event counts into one offline diagnostic bundle for benchmark and frontend debugging workflows.",
            endpoints=("POST /api/capabilities/run_evidence_bundle",),
            input_schema={"route": "dict", "result": "dict", "events": "list", "artifacts": "list"},
            output_schema={"bundle": "run_evidence_bundle.v1"},
            deterministic=True,
            changes_state=False,
            owner="runtime_guards",
            success_signals=("run_evidence_bundle.status", "run_evidence_bundle.route", "run_evidence_bundle.runtime", "run_evidence_bundle.actions", "run_evidence_bundle.extraction", "run_evidence_bundle.failure", "run_evidence_bundle.artifacts", "run_evidence_bundle.debug"),
            fallback_to=("agent_case_benchmark", "failure_fixture_replay", "deterministic_evaluator"),
            milestones=("Y121",),
        ),
        CapabilitySpec(
            name="browser_runtime_doctor",
            category="resource_guard",
            layer="browser_substrate",
            description="Diagnoses browser runtime readiness from existing pool, backend, preflight, drift, and issue-summary snapshots, producing recovery guidance without opening browser sessions.",
            endpoints=("GET /api/capabilities/browser_runtime_doctor", "POST /api/capabilities/browser_runtime_doctor"),
            input_schema={"runtime_status": "browser_runtime.v1", "pool_status": "dict", "backend_status": "dict", "runtime_preflight": "browser_runtime_preflight.v1", "runtime_drift": "browser_runtime_drift.v1", "runtime_issue_summary": "browser_runtime_issue_summary.v1"},
            output_schema={"report": "browser_runtime_doctor_report.v1"},
            deterministic=True,
            changes_state=False,
            owner="runtime_guards",
            success_signals=("browser_runtime_doctor.status", "browser_runtime_doctor.readiness", "browser_runtime_doctor.checks", "browser_runtime_doctor.recommended_actions", "browser_runtime_doctor.recovery_plan"),
            fallback_to=("browser_pool", "browser_backend_abstraction", "task_queue"),
            milestones=("Y122",),
        ),
        CapabilitySpec(
            name="browser_pool",
            category="resource_guard",
            layer="browser_substrate",
            description="Controls browser concurrency and combines pool capacity with active backend status, health, health-cache freshness, non-blocking preflight, runtime drift, and runtime issue summary helper contracts.",
            endpoints=("GET /api/browser_pool",),
            output_schema={"pool": "dict", "runtime": "browser_runtime.v1", "runtime_preflight": "browser_runtime_preflight.v1", "runtime_drift": "browser_runtime_drift.v1", "runtime_issue_summary": "browser_runtime_issue_summary.v1"},
            deterministic=True,
            changes_state=False,
            owner="runtime_guards",
            success_signals=("runtime.status", "runtime_preflight.status", "runtime_drift.status", "runtime_issue_summary.status", "available_slots", "active_contexts", "backend.active.name", "backend.health.status", "backend.health.cache"),
            fallback_to=("task_queue",),
            milestones=("Y8", "Y49", "Y51", "Y52", "Y53", "Y55", "Y56"),
        ),
        CapabilitySpec(
            name="network_intelligence",
            category="data_fast_path",
            layer="data_plane",
            description="Discovers captured XHR/fetch candidates and structured responses before visual scraping.",
            endpoints=("GET /api/runs/{run_id}/network",),
            output_schema={"candidates": "list"},
            deterministic=True,
            changes_state=False,
            owner="deterministic_router",
            success_signals=("candidate_count", "json_shape", "row_count"),
            fallback_to=("api_replay", "generic_extractor"),
            milestones=("Y4",),
        ),
        CapabilitySpec(
            name="api_replay",
            category="data_fast_path",
            layer="data_plane",
            description="Replays captured API candidates for deterministic data extraction and schema validation.",
            endpoints=("POST /api/runs/{run_id}/network/replay",),
            input_schema={"candidate_id": "str", "mode": "dry_run|execute"},
            output_schema={"status_code": "int", "rows": "list"},
            deterministic=True,
            changes_state=False,
            owner="deterministic_router",
            success_signals=("status_code<400", "row_count", "required_fields"),
            fallback_to=("generic_extractor", "spider_lite"),
            milestones=("Y5",),
        ),
        CapabilitySpec(
            name="generic_extractor",
            category="extraction",
            layer="data_plane",
            description="Extracts structured data from JSON, HTML tables, cards, repeated blocks, selectors, and text sources.",
            endpoints=("POST /api/extractor/run", "POST /api/extractor/select"),
            input_schema={"source": "str|dict|list", "requested_fields": "list", "selector": "str"},
            output_schema={"rows": "list", "row_count": "int", "results": "list"},
            deterministic=True,
            changes_state=False,
            owner="deterministic_router",
            success_signals=("row_count", "required_fields", "artifact"),
            fallback_to=("spider_lite", "browser_control", "vision_agent"),
            milestones=("Y6", "Y22"),
        ),
        CapabilitySpec(
            name="extractor_select",
            category="extraction",
            layer="data_plane",
            description="Runs selector-specific extraction against provided source/html for low-risk deterministic execution.",
            endpoints=("POST /api/capabilities/execute",),
            input_schema={"source": "str", "selector": "str", "mode": "str", "output": "str"},
            output_schema={"results": "list", "count": "int"},
            deterministic=True,
            changes_state=False,
            owner="deterministic_router",
            success_signals=("count", "target_count", "verification.passed"),
            fallback_to=("generic_extractor",),
            milestones=("Y31", "Y42"),
        ),
        CapabilitySpec(
            name="item_pipeline",
            category="post_processing",
            layer="data_plane",
            description="Normalizes, validates, deduplicates, filters, and pages extracted item records.",
            endpoints=("GET /api/spider/{run_id}/items",),
            input_schema={"items": "list", "required_fields": "list"},
            output_schema={"items": "list", "total": "int"},
            deterministic=True,
            changes_state=False,
            owner="runtime_guards",
            success_signals=("total", "required_fields", "dedupe_count"),
            fallback_to=("generic_extractor",),
            milestones=("Y28",),
        ),
        CapabilitySpec(
            name="robots_throttle",
            category="crawl_guard",
            layer="runtime_guards",
            description="Checks robots policy and reserves crawl slots before repeated domain fetching.",
            endpoints=("POST /api/robots/check", "POST /api/robots/reserve"),
            input_schema={"url": "str", "obey": "bool"},
            output_schema={"allowed_by_robots": "bool", "delay_seconds": "float"},
            deterministic=True,
            changes_state=True,
            owner="runtime_guards",
            success_signals=("allowed_by_robots", "reserved_until"),
            fallback_to=("human_guard",),
            milestones=("Y23",),
        ),
        CapabilitySpec(
            name="spider_lite",
            category="crawl_extract",
            layer="data_plane",
            description="Runs multi-page controlled crawling with depth/page limits, extraction config, cache, and optional export.",
            endpoints=("POST /api/spider/run", "GET /api/spider/{run_id}", "GET /api/spider/{run_id}/items"),
            input_schema={"start_urls": "list", "max_pages": "int", "extract": "dict"},
            output_schema={"pages": "list", "items": "list", "item_count": "int"},
            deterministic=True,
            changes_state=True,
            owner="deterministic_router",
            success_signals=("item_count", "page_count", "artifact"),
            fallback_to=("browser_control", "vision_agent"),
            milestones=("Y24",),
        ),
        CapabilitySpec(
            name="page_response_cache",
            category="dev_mode",
            layer="data_plane",
            description="Records and replays page responses for deterministic regression and prompt/debug loops.",
            endpoints=("GET /api/spider/page_cache/{session_id}", "GET /api/spider/page_cache/{session_id}/entries"),
            output_schema={"cache_entries": "list", "mode": "record|replay"},
            deterministic=True,
            changes_state=False,
            owner="deterministic_router",
            success_signals=("cache_hit", "entry_count"),
            fallback_to=("spider_lite",),
            milestones=("Y25",),
        ),
        CapabilitySpec(
            name="feed_export",
            category="artifact",
            layer="data_plane",
            description="Exports validated spider/extractor items as JSONL or JSON artifact evidence.",
            endpoints=("POST /api/spider/{run_id}/export",),
            input_schema={"run_id": "str", "format": "jsonl|json"},
            output_schema={"path": "str", "url": "str", "count": "int"},
            deterministic=True,
            changes_state=True,
            owner="runtime_guards",
            success_signals=("artifact.path", "artifact.url", "count"),
            fallback_to=("artifact_manager",),
            milestones=("Y27",),
        ),
        CapabilitySpec(
            name="artifact_manager",
            category="artifact",
            layer="operations_plane",
            description="Registers, lists, and serves execution evidence files and trace artifacts.",
            endpoints=("GET /api/artifacts", "/artifacts/{path}"),
            output_schema={"files": "list", "url": "str"},
            deterministic=True,
            changes_state=True,
            owner="runtime_guards",
            success_signals=("registered_artifact", "download_url"),
            milestones=("Y27", "Y42"),
        ),
        CapabilitySpec(
            name="browser_backend_abstraction",
            category="browser_runtime",
            layer="browser_substrate",
            description="Abstracts BrowserControl session creation behind a backend interface for local Playwright, configurable remote Playwright/CDP endpoints, cached health checks, and future stealth browser providers.",
            endpoints=("GET /api/browser_control/backend",),
            input_schema={"VSPIDER_BROWSER_BACKEND": "playwright|remote_playwright", "VSPIDER_REMOTE_BROWSER_ENDPOINT": "str", "VSPIDER_REMOTE_BROWSER_MODE": "cdp|ws"},
            output_schema={"active": "dict", "health": "dict", "available": "list", "session_count": "int"},
            deterministic=True,
            changes_state=False,
            owner="runtime_guards",
            success_signals=("active.name", "health.status", "health.cache.hit", "available", "session_count", "remote_playwright.status"),
            fallback_to=("browser_pool", "human_guard"),
            milestones=("Y47", "Y48", "Y51", "Y52"),
        ),
        CapabilitySpec(
            name="browser_control",
            category="browser_actions",
            layer="browser_substrate",
            description="Controls isolated browser sessions, snapshots, semantic find, tabs, cookies, storage, guarded actions, unified browser_state.v2 page facts, and self-developed browser action trace, failure taxonomy, reliability scoring, self-healing policy recommendations, plus issue summary contracts for successful and failed crawl, click, fill, selector, similar-element, input, wait, navigation, readback, and screenshot operations.",
            endpoints=("GET /api/browser_control/backend", "POST /api/browser_control/open", "POST /api/browser_control/snapshot", "POST /api/browser_control/find", "POST /api/browser_control/selector", "POST /api/browser_control/similar", "POST /api/browser_control/click", "POST /api/browser_control/fill", "POST /api/browser_control/type", "POST /api/browser_control/hover", "POST /api/browser_control/press", "POST /api/browser_control/scroll", "POST /api/browser_control/wait", "POST /api/browser_control/navigate", "POST /api/browser_control/get", "POST /api/browser_control/screenshot"),
            actions=("open", "snapshot", "find", "selector", "similar", "click", "fill", "type", "hover", "press", "scroll", "wait", "navigate", "get", "screenshot"),
            output_schema={"session_id": "str", "refs": "list[ActionRef]", "snapshot": "dict", "browser_state": "browser_state.v2", "action_trace": "browser_action_trace.v1", "action_trace.issue_summary": "browser_action_issue_summary.v1", "action_reliability": "action_reliability_score.v1", "self_healing_policy": "self_healing_policy.v1"},
            deterministic=False,
            changes_state=True,
            risk="medium",
            owner="vision_model",
            preconditions=("authorized_browser_context",),
            success_signals=("action_ref", "action_result", "browser_state.version", "browser_state.metrics.interactive_count", "browser_state.perception.dom_shape", "action_reliability.score", "action_reliability.risk_level", "self_healing_policy.recommended_actions", "action_trace.status", "action_trace.error", "action_trace.result_summary.failure_code", "action_trace.result_summary.failure_category", "action_trace.result_summary.recovery_actions", "action_trace.action_ref.source", "action_trace.duration_ms", "action_trace.issue_summary.status", "action_trace.issue_summary.issue_count", "readback", "page_state"),
            fallback_to=("selector_generator", "vision_agent", "human_guard"),
            milestones=("Y18", "Y21", "Y69", "Y70", "Y72", "Y76", "Y82", "Y83", "Y104", "Y106"),
            cost="medium",
        ),
        CapabilitySpec(
            name="action_ref_normalizer",
            category="locator_recovery",
            layer="browser_substrate",
            description="Normalizes SoM target_id, browser @e refs, selectors, AX roles, bboxes, and visual points into a single ActionRef contract.",
            endpoints=("GET /api/action_refs/schema", "POST /api/action_refs/normalize"),
            input_schema={"ref": "@e1|som:5", "selector": "str", "role": "str", "bbox": "dict", "point": "list"},
            output_schema={"action_ref": "ActionRef", "summary": "dict"},
            deterministic=True,
            changes_state=False,
            owner="deterministic_router",
            success_signals=("action_ref.version", "action_ref.source", "action_ref.ref"),
            fallback_to=("selector_generator", "vision_agent"),
            milestones=("Y46",),
        ),
        CapabilitySpec(
            name="selector_generator",
            category="locator_recovery",
            layer="browser_substrate",
            description="Generates stable selectors and similar element refs for locator recovery after DOM drift.",
            endpoints=("POST /api/browser_control/selector", "POST /api/browser_control/similar"),
            output_schema={"selector": "str", "similar": "list"},
            deterministic=True,
            changes_state=False,
            owner="deterministic_router",
            success_signals=("selector", "match_count", "similar_refs"),
            fallback_to=("vision_agent",),
            milestones=("Y26",),
        ),
        CapabilitySpec(
            name="action_registry_macros",
            category="agent_tools",
            layer="execution_kernel",
            description="Runs registered deterministic macros and specialized skills selected from the full task goal.",
            actions=("targeted_probe", "auto_form_fill", "chat_extract", "chat_submit", "fetch_links_batch", "next_page"),
            output_schema={"tool": "dict", "evidence": "dict"},
            deterministic=True,
            changes_state=True,
            owner="deterministic_router",
            success_signals=("tool.evidence", "readback", "verification"),
            fallback_to=("browser_control", "vision_agent"),
            milestones=("legacy", "Y18"),
        ),
        CapabilitySpec(
            name="deterministic_evaluator",
            category="evaluation",
            layer="execution_kernel",
            description="Separates planner, executor, and evaluator responsibilities by turning deterministic execution evidence, success verification, browser_state.v2, action reliability scores, and failure bundles into accept, repair, replan, or reject decisions.",
            input_schema={"execution_result": "dict", "route": "dict", "browser_state": "browser_state.v2", "action_reliability": "action_reliability_score.v1"},
            output_schema={"evaluation": "deterministic_evaluation.v1"},
            deterministic=True,
            changes_state=False,
            owner="deterministic_router",
            success_signals=("deterministic_evaluation.decision", "deterministic_evaluation.passed", "deterministic_evaluation.failed_checks", "deterministic_evaluation.recommended_actions"),
            fallback_to=("planner_feedback", "human_guard"),
            milestones=("Y107",),
        ),
        CapabilitySpec(
            name="efficiency_correlation",
            category="evaluation",
            layer="execution_kernel",
            description="Correlates crawl_efficiency_plan.v1 with deterministic evaluation, action reliability, browser_state.v2, and executed capability evidence to explain efficiency alignment or drift without changing execution behavior.",
            input_schema={"execution_result": "dict", "crawl_efficiency_plan": "crawl_efficiency_plan.v1", "deterministic_evaluation": "deterministic_evaluation.v1", "action_reliability": "action_reliability_score.v1", "browser_state": "browser_state.v2"},
            output_schema={"report": "efficiency_correlation_report.v1"},
            deterministic=True,
            changes_state=False,
            owner="deterministic_router",
            success_signals=("efficiency_correlation.status", "efficiency_correlation.alignment", "efficiency_correlation.root_causes", "efficiency_correlation.planner_hints", "efficiency_correlation.recommended_actions"),
            fallback_to=("deterministic_evaluator", "planner_feedback"),
            milestones=("Y111",),
        ),
        CapabilitySpec(
            name="efficiency_feedback",
            category="evaluation",
            layer="execution_kernel",
            description="Projects efficiency_correlation_report.v1 into planner_feedback.v1 candidates for offline review without changing route planning or execution behavior.",
            input_schema={"efficiency_correlation_report": "efficiency_correlation_report.v1"},
            output_schema={"planner_feedback": "planner_feedback.v1"},
            deterministic=True,
            changes_state=False,
            owner="deterministic_router",
            success_signals=("efficiency_feedback.preferred_capabilities", "efficiency_feedback.avoid_capabilities", "efficiency_feedback.avoid_actions", "efficiency_feedback.recommended_actions"),
            fallback_to=("planner_feedback", "semantic_planner_reflector"),
            milestones=("Y113",),
        ),
        CapabilitySpec(
            name="efficiency_feedback_replay",
            category="evaluation",
            layer="execution_kernel",
            description="Offline validator that replays efficiency planner feedback candidates against route and execution_plan contracts without opening browsers, calling models, or changing routing behavior.",
            endpoints=("POST /api/capabilities/efficiency_feedback/replay", "GET /api/capabilities/efficiency_feedback/replays", "POST /api/capabilities/efficiency_feedback/replay_batch"),
            input_schema={"efficiency_correlation_report": "efficiency_correlation_report.v1", "planner_feedback": "planner_feedback.v1"},
            output_schema={"report": "efficiency_feedback_replay_report.v1", "reports": "list[efficiency_feedback_replay_report_summary.v1]", "batch_report": "efficiency_feedback_replay_batch_report.v1"},
            deterministic=True,
            changes_state=False,
            owner="deterministic_router",
            success_signals=("efficiency_feedback_replay.passed", "efficiency_feedback_replay.route", "efficiency_feedback_replay.execution_plan", "efficiency_feedback_replay.failed_checks", "efficiency_feedback_replay.api", "efficiency_feedback_replay.artifact", "efficiency_feedback_replay.artifact_library", "efficiency_feedback_replay.batch", "efficiency_feedback_replay.batch_artifact", "capability_trace.efficiency_feedback_replay_ui", "capability_trace.efficiency_feedback_replay_library_ui"),
            fallback_to=("efficiency_feedback", "planner_feedback"),
            milestones=("Y114", "Y115", "Y116", "Y117", "Y118"),
        ),
        CapabilitySpec(
            name="planner_feedback_shadow",
            category="evaluation",
            layer="execution_kernel",
            description="Offline shadow evaluator that compares baseline route/execution_plan contracts with a copied planner-feedback-injected plan to estimate feedback impact without changing router or execution behavior.",
            endpoints=("POST /api/capabilities/efficiency_feedback/shadow",),
            input_schema={"efficiency_correlation_report": "efficiency_correlation_report.v1", "planner_feedback": "planner_feedback.v1", "goal": "str", "url": "str"},
            output_schema={"report": "planner_feedback_shadow_report.v1"},
            deterministic=True,
            changes_state=False,
            owner="deterministic_router",
            success_signals=("planner_feedback_shadow.baseline", "planner_feedback_shadow.delta", "planner_feedback_shadow.no_route_decision_change", "planner_feedback_shadow.feedback_step"),
            fallback_to=("efficiency_feedback_replay", "planner_feedback"),
            milestones=("Y119",),
        ),
        CapabilitySpec(
            name="semantic_planner_reflector",
            category="model_reasoning",
            layer="model_plane",
            description="Uses text/semantic model reasoning for decomposition, stalled-run audit, and retry/abort decisions.",
            actions=("VLMClient.make_plan", "VLMClient.reflect"),
            input_schema={"goal": "str", "history": "list", "signals": "dict"},
            output_schema={"plan": "list", "reflection": "dict"},
            deterministic=False,
            changes_state=False,
            risk="medium",
            owner="semantic_model",
            success_signals=("subgoals", "decision", "reason"),
            fallback_to=("vision_agent", "human_guard"),
            milestones=("existing",),
            cost="medium",
        ),
        CapabilitySpec(
            name="vision_agent",
            category="visual_grounding",
            layer="model_plane",
            description="Uses screenshot plus AX/SoM context for ambiguous visible target grounding after deterministic paths fail.",
            actions=("VLMClient.ask", "BrowserEnv.mark_and_screenshot"),
            input_schema={"screenshot": "base64", "goal": "str", "ax_tree": "str"},
            output_schema={"action": "dict", "thought": "str"},
            deterministic=False,
            changes_state=True,
            risk="medium",
            owner="vision_model",
            success_signals=("valid_action_schema", "action_result", "verification"),
            fallback_to=("human_guard",),
            milestones=("existing",),
            cost="high",
        ),
        CapabilitySpec(
            name="human_guard",
            category="safety",
            layer="runtime_guards",
            description="Escalates CAPTCHA, 2FA, auth walls, stale sessions, and high-risk operations instead of blind retries.",
            actions=("ask_human", "manual_auth"),
            input_schema={"reason": "str", "evidence": "dict"},
            output_schema={"human_required": "bool", "reason": "str"},
            deterministic=True,
            changes_state=False,
            risk="medium",
            owner="runtime_guards",
            preconditions=("auth_or_captcha_detected",),
            success_signals=("human_required", "safe_abort", "session_refreshed"),
            milestones=("existing",),
        ),
    ]
    return {spec.name: spec for spec in specs}


def list_capabilities(
    *,
    category: str | None = None,
    layer: str | None = None,
    include_disabled: bool = False,
) -> list[dict[str, Any]]:
    capabilities = build_default_capability_manifest().values()
    rows: list[dict[str, Any]] = []
    for spec in capabilities:
        if not include_disabled and not spec.enabled:
            continue
        if category and spec.category != category:
            continue
        if layer and spec.layer != layer:
            continue
        rows.append(spec.to_dict())
    return rows


def get_capability(name: str) -> dict[str, Any] | None:
    spec = build_default_capability_manifest().get(str(name or ""))
    return spec.to_dict() if spec else None


def summarize_capabilities(names: list[str]) -> list[dict[str, Any]]:
    manifest = build_default_capability_manifest()
    rows: list[dict[str, Any]] = []
    seen: set[str] = set()
    for name in names:
        key = str(name or "")
        if not key or key in seen:
            continue
        seen.add(key)
        spec = manifest.get(key)
        if spec:
            rows.append({
                "name": spec.name,
                "category": spec.category,
                "layer": spec.layer,
                "owner": spec.owner,
                "deterministic": spec.deterministic,
                "risk": spec.risk,
                "cost": spec.cost,
                "success_signals": list(spec.success_signals),
                "fallback_to": list(spec.fallback_to),
            })
    return rows
